routes.py
import os
from werkzeug.utils import secure_filename
from flask_apscheduler import APScheduler
from flask import Flask, render_template, request, redirect, url_for, session, flash, Blueprint, jsonify, Response
import sqlite3
import hashlib
import cv2
import dlib
import numpy as np
import uuid
from datetime import datetime, timedelta
import random
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
import atexit

routes_bp = Blueprint('routes', __name__, url_prefix='')

@routes_bp.route('/')
def index():
    return render_template('login.html')

UPLOAD_FOLDER = 'static/ProfilePictures'
DATABASE_FOLDER = 'database'


#################################### Fuction to save profile pictures Start ####################################

def save_profile_picture(file, user_role, fname, lname, userid):
    subfolder = 'Faculty' if user_role == 'faculty' else 'Student'
    folder_path = os.path.join(UPLOAD_FOLDER, subfolder)
    os.makedirs(folder_path, exist_ok=True)
    
    ext = secure_filename(file.filename).rsplit('.', 1)[1].lower()
    filename = f"{fname}_{lname}_{userid}.{ext}"
    file_path = os.path.join(folder_path, filename)
    
    file.save(file_path)
    return file_path

#################################### Fuction to save profile pictures End ####################################

#################################### Route for Team Page Start  ####################################

@routes_bp.route('/team')
def team():
    return render_template('team.html')

#################################### Route for Team Page Start  ####################################


#################################### Route for Student Signup Start ####################################

@routes_bp.route('/studentsignup', methods=['GET', 'POST'])
def studentsignup():
    if request.method == 'POST':
        userid = request.form['userid']
        if is_userid_existing(userid):
            flash('User ID already exists. Please choose another.', 'error')
            return redirect(url_for('.studentsignup'))
        
        fname = request.form['fname']
        lname = request.form.get('lname')  
        dob = request.form.get('dob')  
        collegename = request.form['collegename']
        departmentname = request.form['departmentname']
        semester = request.form['semester']
        section = request.form['section']
        profile_picture = request.files['profilepicture']
        profile_picture_path = save_profile_picture(profile_picture, 'student', fname, lname, userid)
        password = request.form['password']
        email = request.form['email']
        phonenumber = request.form['phonenumber']
        hashed_password = hashlib.sha256(password.encode()).hexdigest()
        start_year = int(request.form['startYear'])
        end_year = int(request.form['endYear'])
        LEET = request.form['leetStudent']
        
        if LEET == 'yes':
            start_year -= 1
        
        batch = f"{start_year}-{end_year}"
        
        db_path = os.path.join(DATABASE_FOLDER, 'Students.db')
        conn = sqlite3.connect(db_path)
        c = conn.cursor()
        
        c.execute('''
                  CREATE TABLE IF NOT EXISTS users (
                      id INTEGER PRIMARY KEY,
                      userid INTEGER NOT NULL,
                      fname TEXT NOT NULL,
                      lname TEXT,
                      dob TEXT,
                      collegename TEXT,
                      departmentname TEXT,
                      semester TEXT,  
                      section TEXT,    
                      profile_picture TEXT,
                      password TEXT NOT NULL,
                      role TEXT DEFAULT 'student',  
                      verified TEXT DEFAULT 'pending',
                      email TEXT,
                      phonenumber INTEGER,
                      batch TEXT,
                      LEET TEXT
                  )
                  ''')
        
        c.execute("INSERT INTO users (userid, fname, lname, dob, collegename, departmentname, semester, section, profile_picture, password, role, email, phonenumber, batch, LEET) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
          (userid, fname, lname, dob, collegename, departmentname, semester, section, profile_picture_path, hashed_password, 'student', email, phonenumber, batch, LEET))
        
        conn.commit()
        conn.close()
        
        flash('You have successfully signed up!', 'success')
        return redirect(url_for('.studentdashboard'))
    
    return render_template('studentsignup.html')

#################################### Route for Student Signup End ####################################


#################################### Route for Student Verification Start ####################################

@routes_bp.route('/set_profile_status', methods=['POST'])
def set_profile_status():
    try:
        data = request.json
        userid = data.get('userId')
        status = data.get('status')
        semester = data.get('semester')
        section = data.get('section')

        conn = sqlite3.connect('database/Students.db')
        cursor = conn.cursor()

        cursor.execute("UPDATE users SET verified = ? WHERE userid = ? AND semester = ? AND section = ?", (status, userid, semester, section))
        conn.commit()

        cursor.close()
        conn.close()

        return jsonify({'message': f"Status updated to {status} for user ID {userid}"}), 200

    except Exception as e:
        error_message = f"Error setting verification status: {str(e)}"
        print(error_message)
        return jsonify({'error': error_message}), 500




#################################### Route for Student Verification Start ####################################

#################################### Route to check whether the userid exists or not Start ####################################

@routes_bp.route('/check_userid', methods=['POST'])
def check_userid():
    userid = request.form['userid']
    if is_userid_existing(userid):
        return jsonify({'exists': True})
    else:
        return jsonify({'exists': False})

def is_userid_existing(userid):
    student_db_path = os.path.join(DATABASE_FOLDER, 'Students.db')
    conn_student = sqlite3.connect(student_db_path)
    c_student = conn_student.cursor()
    c_student.execute("SELECT userid FROM users WHERE userid=?", (userid,))
    existing_userid_student = c_student.fetchone()
    conn_student.close()
    
    faculty_db_path = os.path.join(DATABASE_FOLDER, 'FacultyMember.db')
    conn_faculty = sqlite3.connect(faculty_db_path)
    c_faculty = conn_faculty.cursor()
    c_faculty.execute("SELECT userid FROM users WHERE userid=?", (userid,))
    existing_userid_faculty = c_faculty.fetchone()
    conn_faculty.close()
    
    return existing_userid_student is not None or existing_userid_faculty is not None

#################################### Route to check whether the userid exists or not End ####################################


#################################### Route to check whether the userid present or not Start ####################################

@routes_bp.route('/userid_present', methods=['GET'])
def userid_present():
    role = request.args.get('role')
    userid = request.args.get('userid')
    
    if role == 'Student':
        db_path = os.path.join(DATABASE_FOLDER, 'Students.db')
    elif role == 'Faculty':
        db_path = os.path.join(DATABASE_FOLDER, 'FacultyMember.db')
    else:
        return jsonify({'exists': False}), 400
    
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    c.execute("SELECT 1 FROM users WHERE userid=?", (userid,))
    user_exists = c.fetchone() is not None
    conn.close()
    
    return jsonify({'exists': user_exists})

#################################### Route to check whether the userid present or not End ####################################


#################################### Route to check whether the phone number exists or not Start ####################################

@routes_bp.route('/check_phonenumber', methods=['POST'])
def check_phonenumber():
    phonenumber = request.form['phonenumber']
    if is_phonenumber_existing(phonenumber):
        return jsonify({'exists': True})
    else:
        return jsonify({'exists': False})

def is_phonenumber_existing(phonenumber):
    student_db_path = os.path.join(DATABASE_FOLDER, 'Students.db')
    conn_student = sqlite3.connect(student_db_path)
    c_student = conn_student.cursor()
    c_student.execute("SELECT phonenumber FROM users WHERE phonenumber=?", (phonenumber,))
    existing_phonenumber = c_student.fetchone()
    conn_student.close()
    
    return existing_phonenumber is not None

#################################### Route to check whether the phone number exists or not End ####################################


#################################### Route for facultysignup Start ####################################

@routes_bp.route('/facultysignup', methods=['GET', 'POST'])
def facultysignup():
    if request.method == 'POST':
        userid = request.form['userid']
        if is_userid_existing(userid):
            flash('User ID already exists. Please choose another.', 'error')
            return redirect(url_for('.facultysignup'))
        fname = request.form['fname']
        lname = request.form.get('lname')  
        dob = request.form.get('dob')  
        collegename = request.form['collegename']
        departmentname = request.form['departmentname']
        role = request.form['role']
        if role == 'Academic Coordinator':
            semesters = request.form.getlist('semesterAC') 
            designation = request.form['InstDesig']  
        elif role == 'TPP Instructor':
            subject = request.form['tpp']                  
        elif role == 'Instructor':
            designation = request.form['InstDesig']      
        elif role == 'Class Counselor':

templates/admin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="../static/output.css">
    <link rel="shortcut icon" href="../static/Assets/favicon.ico" type="image/x-icon">
    <style>
      .alert {
        background-color: #6ee7b7;
        color: #064e3b;
        display: block;
        position: relative;
        padding: 0.75rem;
        margin-bottom: 1rem;
        border: 1px solid transparent;
        border-radius: 0.25rem;
      }
    </style>
  </head>
  <body>
    <header>{% include 'header.html' %}</header>
    <h1>Admin Dashboard</h1>
    <table border="1">
      <thead>
        <tr>
          <th>User ID</th>
          <th>Name</th>
          <th>College Name</th>
          <th>Department Name</th>
          <th>Role</th>
          <th>Photo</th>
          <th>Action</th>
          <!-- Add more columns as needed -->
        </tr>
      </thead>
      <tbody>
        {% for user in pending_users %}
        <tr>
          <td>{{ user[1] }}</td>
          <td>{{ user[2] }} {{ user[3] }}</td>
          <td>{{ user[5] }}</td>
          <td>{{ user[6] }}</td>
          <td>{{ user[7] }}</td>
          <td><img src="{{ user[8] }}" alt="Profile Picture" /></td>
          <td>
            <form
              action="{{ url_for('routes.verify_user', user_id=user[1]) }}"
              method="post"
            >
              <input type="hidden" name="action" value="verify" />
              <button type="submit">Verify</button>
            </form>
            <form
              action="{{ url_for('routes.verify_user', user_id=user[1]) }}"
              method="post"
            >
              <input type="hidden" name="action" value="not_verify" />
              <button type="submit">Not Verify</button>
            </form>
          </td>
          <!-- Add more columns as needed -->
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <form action="{{ url_for('routes.logout') }}" method="post">
      <button type="submit">Log out</button>
    </form>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'Verification' %}
    <div class="items-center flex alert" role="alert">
      <span><strong>{{ category }}</strong> {{ message }}</span>
      <span class="close-btn" onclick="this.parentElement.style.display='none';"
        >&times;</span
      >
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
  </body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="shortcut icon"
      href="../static/Assets/favicon.ico"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="../static/output.css" />
    <style>
      .dropdown-content {
        display: none;
        position: absolute;
        z-index: 1;
        transition: all 0.5s ease-in-out;
      }

      .dropdown:hover .dropdown-content {
        display: block;
      }
    </style>
  </head>
  <body>
    <footer
      class="mt-8 flex items-center justify-between py-4 bg-white px-4 xl:px-64 lg:px-12 sm:px-6 shadow-sm"
    >
      <div class="left">
        <img src="../static/Assets/logo.webp" alt="" style="width: 130px" />
      </div>
      <div class="right dropdown">
        {% if profile_picture %}
        <img
          src="{{ profile_picture }}"
          alt=""
          style="
            border-radius: 50%;
            height: 30px;
            margin-bottom: 3px;
            aspect-ratio: 1;
          "
        />
        {% else %}
        <img
          src="../static/Assets/user.svg"
          alt=""
          style="border-radius: 50%; height: 30px; margin-bottom: 3px"
        />
        {% endif %}
        <div
          class="dropdown-content right-64 bg-white w-48 h-28 border border-gray-300 rounded-md shadow-md p-2"
        >
          <div class="up flex items-center">
            <div class="upleft">
              {% if profile_picture %}
              <img
                src="{{ profile_picture }}"
                alt=""
                style="
                  border-radius: 50%;
                  height: 40px;
                  width: 40px;
                  margin-bottom: 3px;
                "
              />
              {% else %}
              <img
                src="../static/Assets/user.svg"
                alt=""
                style="
                  border-radius: 50%;
                  height: 40px;
                  width: 40px;
                  margin-bottom: 3px;
                "
              />
              {% endif %}
            </div>
            <div class="upright ml-2 text-xs">
              <p class="font-semibold">{{ fname }} {{ lname }}</p>
              <p>{{ designation }}</p>
              <p>{{ role }}</p>
            </div>
          </div>
          <div class="down">
            <form action="{{ url_for('routes.logout') }}" method="post">
              <button type="submit" class="text-xs mx-auto w-full mt-4 border py-1 rounded-lg transition-colors ease-in-out duration-300 hover:bg-black/80 hover:text-white hover:border-black/80">Sign Out</button>
            </form>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <link rel="shortcut icon" href="../static/Assets/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="../static/output.css" />
  <style>
    /* Add CSS for dropdown menu */
    .dropdown-menu {
      display: none;
    }

    .profile:hover .dropdown-menu {
      display: block;
    }
  </style>
</head>

<body>
  <nav class="py-3 bg-white shadow-sm px-3 max-[500px]:py-2">
    <div class="flex items-center justify-between max-w-screen-2xl mx-auto">
      <div class="left">
        <img src="../static/Assets/logo.webp" alt="" style="width: 130px" />
      </div>
      <div class="right flex item-center space-x-4">
        <div class="relative flex text-left profile">
          <div class="text-sm font-semibold mr-2 max-[700px]:hidden">
            <p>{{ fname }} {{ lname }}</p>
            <p>{{ userid }}</p>
          </div>
          <div class="relative inline-block text-left profile">
            <div>
              <div class="inline-flex w-full justify-center gap-x-1.5 rounded-md" id="menu-button" aria-expanded="true"
                aria-haspopup="true">
                {% if profile_picture %}
                <div class="rounded-full overflow-auto object-cover w-10 h-10"><img src="{{ profile_picture }}"
                    alt="User Profile Picture" class="w-10 h-10 aspect-square" />
                </div>
                {% else %}
                <img src="../static/Assets/user.svg" alt="" style="border-radius: 50%; height: 30px;" />
                {% endif %}
              </div>
            </div>
            <div
              class="dropdown-menu absolute p-4 max-[500px]:py-2 max-[500px]:px-2 right-0 z-10 w-56 origin-top-right rounded-md bg-white drop-shadow-lg"
              role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
              <div class="py-1" role="none">
                <div class="up flex items-center">
                  <div class="upleft">
                    {% if profile_picture %}
                    <div class="rounded-full overflow-auto object-cover w-[40px] h-[40px] mb-[3px]"><img
                        src="{{ profile_picture }}" alt="User Profile Picture"
                        class="w-[40px] h-[40px] aspect-square" />
                    </div>
                    {% else %}
                    <img src="../static/Assets/user.svg" alt="" style="
                      border-radius: 50%;
                      height: 40px;
                      width: 40px;
                      margin-bottom: 3px;
                    " />
                    {% endif %}
                  </div>
                  <div class="upright ml-2 text-sm">
                    <p class="font-semibold">{{ fname }} {{ lname }}</p>
                    <p>{{ designation }}</p>
                    <p>{{ role }}</p>
                    <p>{{ semester }} {{ section }}</p>
                  </div>
                </div>
                <div class="down">
                  <form action="{{ url_for('routes.logout') }}" method="post">
                    <button type="submit"
                      class="text-xs mx-auto w-full mt-4 border py-2 rounded-lg transition-colors ease-in-out duration-300 hover:bg-gray-100 hover:border-gray-300">Sign
                      Out</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </nav>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>MyCGC - Login</title>
  <link rel="stylesheet" href="../static/output.css" />
  <link rel="shortcut icon" href="../static/Assets/favicon.ico" type="image/x-icon" />
  <style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      width: auto;
      -webkit-appearance: none;
      margin: 0;
    }

    input[type="number"] {
      appearance: none;
    }

    .error-message {
      display: block;
      position: relative;
      padding: 0.75rem;
      margin-bottom: 1rem;
      border: 1px solid transparent;
      border-radius: 0.25rem;
    }

    .close-btn {
      position: absolute;
      top: 0.5rem;
      right: 0.5rem;
      cursor: pointer;
    }

    .dropdown-content {
      display: none;
      position: absolute;
      min-width: 120px;
      text-align: center;
      z-index: 1;
      border-radius: 5px;
    }

    .dropdown-content a {
      color: black;
      padding: 7px;
      display: block;
      text-decoration: none;
      transition: all 0.1s ease-in-out;
    }

    .dropdown-content a:hover {
      text-decoration: underline;
    }

    .dropdown:hover .dropdown-content {
      display: block;
    }

    .left {
      -webkit-box-shadow: 0px 0px 5px 3px rgba(0, 0, 0, 0.05);
      -moz-box-shadow: 0px 0px 5px 3px rgba(0, 0, 0, 0.05);
      box-shadow: 0px 0px 5px 3px rgba(0, 0, 0, 0.05);
    }
  </style>
</head>

<body class="bg-black overflow-hidden max-[900px]:bg-white">
  <main class="h-screen w-screen relative flex justify-center items-center">
    <div class="absolute top-0 left-0 w-full h-full bg-cover bg-center opacity-70 max-[900px]:hidden"
      style="background-image: url('../static/Assets/Hero.webp');"></div>
    <div class="absolute bottom-0 left-0 w-full">
      <img src="../static/Assets/HeroOverlay.png" alt="" class="w-full opacity-80 max-[900px]:hidden">
    </div>
    <div
      class="left bg-neutral-50 max-[900px]:bg-white rounded-xl flex flex-col w-[500px] p-8 absolute top-1/2 right-0 mr-20 transform -translate-y-[55%] max-[900px]:right-auto max-[900px]:left-auto max-[900px]:mr-0 max-[520px]:w-[95%] max-[500px]:p-6 max-[900px]:mb-auto">
      <section>
        <div class="">
          <img src="../static/Assets/logo.webp" alt="CGC Landran" class="w-[250px] max-[500px]:w-[200px]" />
          <div class="flex items-center justify-center mt-8 max-[500px]:mt-4">
            <div class="w-full">
              <h2 class="text-3xl font-bold leading-tight text-black sm:text-4xl">
                Sign in
              </h2>
              <div class="flex items-center mt-2 text-gray-600 text-sm max-[350px]:text-xs">
                <p class="">Don't have an account?</p>
                <div class="dropdown ml-1">
                  <a
                    class="transition-all text-blue-700 font-bold duration-200 hover:underline cursor-pointer select-none">
                    Create an account
                  </a>
                  <div class="dropdown-content shadow-md bg-white">
                    <a href="{{ url_for('routes.studentsignup') }}">Student</a>
                    <a href="{{ url_for('routes.facultysignup') }}">Faculty</a>
                  </div>
                </div>
              </div>
              <form method="post" action="{{ url_for('routes.login') }}" class="mt-8 max-[500px]:mt-4">
                <div class="space-y-5 max-[500px]:space-y-3">
                  <div>
                    <label for="indicate" class="text-base font-medium text-gray-900">
                      Please indicate your role:
                    </label>
                    <div class="mt-2">
                      <input type="radio" id="Student" name="role" value="Student" checked />&nbsp;
                      <label for="Student" class="text-gray-400">Student</label>&nbsp;&nbsp;
                      <input type="radio" id="Faculty" name="role" value="Faculty" />&nbsp;
                      <label for="Faculty" class="text-gray-400">Faculty</label>
                    </div>
                  </div>
                  <div>
                    <label for="userid" class="text-base font-medium text-gray-900">
                      User ID
                    </label>
                    <div class="mt-2">
                      <input
                        class="flex h-10 w-full rounded-md border border-gray-300 bg-transparent px-3 py-2 text-sm placeholder:text-gray-400 focus:outline-none"
                        type="text" placeholder="Student ID or Faculty ID" id="userid" name="userid" required />
                    </div>
                    <div id="userid-present-error" class="text-sm text-red-600 font-bold mt-2"></div>
                  </div>
                  <div>
                    <div class="flex items-center justify-between">
                      <label for="password" class="text-base font-medium text-gray-900">
                        Password
                      </label>
                    </div>
                    <div class="mt-2">
                      <input
                        class="flex h-10 w-full rounded-md border border-gray-300 bg-transparent px-3 py-2 text-sm placeholder:text-gray-400 focus:outline-none"
                        type="password" placeholder="Password" id="password" name="password" required />
                    </div>
                  </div>
                  {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category,
                  message in messages %} {% if category == 'error' or category == 'alert' %}
                  <div
                    class="error-message items-center flex {% if category == 'error' %} bg-red-100 {% elif category == 'alert' %} bg-yellow-200 {% endif %}"
                    role="alert">
                    <strong>{{ category }}</strong> {{ message }}
                    <span class="close-btn" onclick="this.parentElement.style.display='none';">&times;</span>
                  </div>
                  {% endif %} {% endfor %} {% endif %} {% endwith %}
                  <div>
                    <button type="submit" value="Log In"
                      class="inline-flex w-full items-center justify-center rounded-md bg-black py-2.5 font-semibold leading-7 text-white transition ease-in-out delay-100 hover:bg-black/80">
                      Sign in
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="ml-2">
                        <line x1="5" y1="12" x2="19" y2="12"></line>
                        <polyline points="12 5 19 12 12 19"></polyline>
                      </svg>
                    </button>
                  </div>
                </div>
              </form>
              <a href="{{ url_for('routes.team') }}" class="inline-block items-center">
                <div class="flex items-center mt-2">
                  <img src="../static/Assets/developer.svg" alt="" style="height: 15px" />
                  <p class="text-gray-400 text-sm ml-1.5">Developer Team</p>
                </div>
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  </main>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const roleRadios = document.querySelectorAll('input[name="role"]');
      const useridInput = document.getElementById("userid");
      const signInButton = document.querySelector('button[type="submit"]');
      const errorDiv = document.getElementById("userid-present-error");

      function updatePlaceholder() {
        if (document.getElementById("Student").checked) {
          useridInput.placeholder = "Enter your Student ID";
        } else if (document.getElementById("Faculty").checked) {
          useridInput.placeholder = "Enter your Faculty ID";
        }
      }

      roleRadios.forEach(function (radio) {
        radio.addEventListener("change", updatePlaceholder);
      });

      function isRoleSelected() {
        return [...roleRadios].some(radio => radio.checked);
      }

      function checkRoleAndEnableButton() {
        if (isRoleSelected()) {
          signInButton.disabled = false;
          signInButton.style.cursor = "pointer";
        } else {
          signInButton.disabled = true;
          signInButton.style.cursor = "not-allowed";
        }
      }

      document.querySelector("form").addEventListener("submit", function (event) {
        if (!isRoleSelected()) {
          event.preventDefault();
        }
      });

      useridInput.addEventListener("blur", function () {
        const role = document.querySelector('input[name="role"]:checked').value;
        const userid = useridInput.value;

        if (userid) {
          fetch(`/userid_present?role=${role}&userid=${userid}`)
            .then(response => response.json())
            .then(data => {
              if (data.exists) {
                errorDiv.textContent = '';
              } else {
                if (role === 'Student') {
                  errorDiv.textContent = 'User ID does not exist in Student Database.';
                } else if (role === 'Faculty') {
                  errorDiv.textContent = 'User ID does not exist in Faculty Database.';
                }
              }
            })
            .catch(error => {
              console.error('Error:', error);
            });
        }
      });

      updatePlaceholder();
      checkRoleAndEnableButton();
    });
  </script>
</body>

</html>

templates/sections.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/output.css">
    <title>Sections</title>
  </head>
  <body>
    <select
      id="section"
      name="section"
      class="rounded-md border-gray-300 text-gray-400 w-full"
    >
      <option>
        Select your Section
        <section></section>
      </option>
      <option value="A1">A1</option>
      <option value="A2">A2</option>
      <option value="B1">B1</option>
      <option value="B2">B2</option>
      <option value="C1">C1</option>
      <option value="C2">C2</option>
      <option value="D1">D1</option>
      <option value="D2">D2</option>
      <option value="E1">E1</option>
      <option value="E2">E2</option>
      <option value="F1">F1</option>
      <option value="F2">F2</option>
    </select>
  </body>
</html>

templates/team.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyCGC - Developer Team</title>
    <link rel="stylesheet" href="../static/output.css">
    <link rel="shortcut icon" href="../static/Assets/favicon.ico" type="image/x-icon">
</head>
<body>
    <h1>Hello for our team</h1>
    <header>
        {% include 'header.html' %}
    </header>
</body>
</html>